### ISSUE TITLE
wHaTs SkYbLoCkAdDoNs

### ISSUE THREAD

**Issue by Zordlan** [MicrocontrollersDev/Skyblock-Extras-Alternatives#10]
![image](https://user-images.githubusercontent.com/69115669/114628748-3c7a9680-9c6c-11eb-84c1-98ed2323603a.png)
hElP i DoNt KnOw WhAt SkYbLoCkAdDoNs Is

**Comment by MicrocontrollersDev** [comment]
shouldn't you be working on BetterCIT?
