### ISSUE TITLE
Add credits

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MicrocontrollersDev/Skyblock-Extras-Alternatives#8]
- pr contributors
- screenshot providers
- other stuff i’m probably forgetting
- oh yeah and see if can make cool like luna does

**Comment by stef-the** [comment]
@MicrocontrollersDev this is done right?

**Comment by MicrocontrollersDev** [comment]
all but last bullet point

**Comment by MicrocontrollersDev** [comment]
closing for now, credits list is getting too long and not all using github so i’d have to use the ever changing discord pfps. also this is work
